; Look at https://community.bistudio.com/wiki/DIK_KeyCodes#DIK_Codes_for_QWERTY for key values

[Menu]

[InGame]
BlimpCamMouseModeSwitch = 0     // Mouse moves blimp camera instead of rotating
								// NOT ONLINE COMPATIBLE! / Default = 0
Input.Fuse = 0x30               // B      / Default = 0x21 - F

[WormAiming]
Input.AimUp = 0x13              // R      / Default = 0xC8 - UP
Input.AimDown = 0x21            // F      / Default = 0xD0 - DOWN
Input.TurnLeft = 0x2C           // Z      / Default = 0xCB - LEFT
Input.TurnRight = 0x2D          // X      / Default = 0xCD - RIGHT

[WormFirstPersonAiming]
Input.AimUp = 0x11              // W      / Default = 0xC8 - UP
Input.AimDown = 0x1F            // S      / Default = 0xD0 - DOWN
Input.TurnLeft = 0x1E           // A      / Default = 0xCB - LEFT
Input.TurnRight = 0x20          // D      / Default = 0xCD - RIGHT

[WormMoving]
Input.Jump = 0x39               // SPACE  / Default = 0x1C - RETURN

[WormRoping]
NinjaRope.Shorten = 0x11        // W      / Default = 0xC8 - UP
NinjaRope.Lengthen = 0x1F       // S      / Default = 0xD0 - DOWN
NinjaRope.SwingForward = 0x20   // D      / Default = 0xCD - RIGHT
NinjaRope.SwingBackward = 0x1E  // A      / Default = 0xCB - LEFT
NinjaRope.SwingLeft = 0x10      // Q      / Default = 0x1E - A
NinjaRope.SwingRight = 0x12     // E      / Default = 0x20 - D

[UtilityGirder]
Girder.Place = 0x36             // RSHIFT / Default = 0x39 - SPACE
Girder.Cancel = 0x39            // SPACE  / Default = 0x0E - BACK
Girder.ChangeType = 0x0F        // TAB    / Default = 0x1C - RETURN
Girder.Rotate.Forward = 0x13    // R      / Default = 0x11 - W
Girder.Rotate.Backward = 0x21   // F      / Default = 0x1F - S
Girder.Rotate.Left = 0x2C       // Z      / Default = 0x1E - A
Girder.Rotate.Right = 0x2D      // X      / Default = 0x20 - D
Girder.Move.Forward = 0x11      // W      / Default = 0xC8 - UP
Girder.Move.Backward = 0x1F     // S      / Default = 0xD0 - DOWN
Girder.Move.Left = 0x1E         // A      / Default = 0xCB - LEFT
Girder.Move.Right = 0x20        // D      / Default = 0xCD - RIGHT

[Flying]
Fly.Pitch.Up = 0x11             // W      / Default = 0xC8 - UP
Fly.Pitch.Down = 0x1F           // S      / Default = 0xD0 - DOWN
Fly.Roll.Left = 0x1E            // A      / Default = 0xCB - LEFT
Fly.Roll.Right = 0x20           // D      / Default = 0xCD - RIGHT
Fly.Yaw.Left = 0x10             // Q      / Default = 0x1E - A
Fly.Yaw.Right = 0x12            // E      / Default = 0x20 - D

[CameraSelect]

[Fire]
Input.Fire = 0x36               // RSHIFT / Default = 0x39 - SPACE

[UtilityFire]
Input.FireUtil = 0x36           // RSHIFT / Default = 0x39 - SPACE
Input.Fire = 0x2A               // LSHIFT / Default = 0x0E - BACK

[CrateChuteRelease]

[Spectator]

[NetworkSpectator]

[AttractMode]
