[Main]
AspectRatioFix = 1
SleepFix = 1            // Fix thread sleep
FrameInterval = 16      // Interval between frames (ms) / Default = 16 (~62 FPS)

[Options]
; Fullscreen = 0          // Run fullscreen/windowed   / overrides /FS /WIN
Borderless = 1          // Run borderless window, only works in windowed
; NoMusic = 0             // Disable background music  / overrides /MUSIC /NOMUSIC
; NoVoices = 0            // Disable worm voices       / overrides /SHUTUP

; NoMovies = 0            // Disable all movies        / overrides /NOMOVIES
; NoMoviesIntro = 0       // Disable intro movies      / overrides /NOLOGOMOVIE
; NoHUD = 0               // Hide HUD elements in game / overrides /NOHUD
; Screenshots = 0         // Save screenshots (PrtSc)  / overrides /ALLOWSCREENSHOTS
; OnscreenKeyboard = 0    // Enable software keyboard  / overrides /KEY
; InvertMouseFP = 0       // Invert first person Y     / overrides /INVERTMOUSEFP
; InvertMouseTP = 0       // Invert third person Y     / overrides /INVERTMOUSETP
; AlternativeJumping = 0  // Enable jump mode 2        / overrides /JUMP2
; ManualCamera = 0        // Enable manual camera (M)  / overrides /MANUALCAMERA
; UnlockAllMissions = 0   // Access to all missions    / overrides /ALLMISSIONS
; Leet = 0                // Upside down worms         / overrides /1337
; ExportAsciiSchemes = 0  // Save 'Schemes Ascii Data.txt'

;; Developer options (some may not work, use at your own risk): 1 = enabled, 0 = disabled
; Autorun =               // run game after game              / overrides /AUTORUN
; Telnet =                // enable telnet                    / overrides /TELNET /NOTELNET
; Bundles =               // use bundles                      / overrides /BUNDLE
; SaveBundles =           // save bundles (implies /BUNDLE)   / overrides /SAVEBUNDLE
; EnemyAI =               // enable/disable AI                / overrides /AI /NOAI
; CliffStop =             // cliff stop                       / overrides /CLIFFSTOP
; Overlay =               // display the overlay              / overrides /OVERLAY /NOOVERLAY
; DebugUpdate =           // ?                                / overrides /DEBUGUPDATE /NODEBUGUPDATE
; DebugInfo =             // display debug information        / overrides /SHOWDEBUGINFO /NODEBUGINFO
; CacheData =             // cache data (requires more mem)   / overrides /CACHEDATA
; AimingRings =           // ?                                / overrides /AIMINGRINGS
; BuildPS2Sound =         // ?                                / overrides /BUILDPS2SOUND
; QuitAfterBuild =        // quit after building resources    / overrides /QUITAFTERBUILD
; Buttons =               // ?                                / overrides /BUTTONS
; Zip =                   // ?                                / overrides /ZIP
; ShowNetBandwith =       // ?                                / overrides /SHOWNETBANDWITH
; Xray =                  // ?                                / overrides /XRAY
; SaveDataFiles =         // ?                                / overrides /SAVEDATAFILES
; Option04 =              // ? additional menu tweak          / overrides /MENU
; Option05 =              // ? maybe screensaver
; Option14 =              // ?
; Option15 =              // ?
; Option16 =              // ?
; Option17 =              // ?
; Option26 =              // ?
; Option29 =              // ?
; Option32 =              // ?
; Option39 =              // ?                          / overrides /HOST /JOIN

[GameSpy]
Host = openspy.net      // GameSpy server host / Default = gamespy.com
